CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS_SERVER = server.c
SRCS_CLIENT = client.c
OBJS_SERVER = $(SRCS_SERVER:.c=.o)
OBJS_CLIENT = $(SRCS_CLIENT:.c=.o)
NAME_SERVER = server
NAME_CLIENT = client

SRCS_SERVER_BONUS = server_bonus.c
SRCS_CLIENT_BONUS = client_bonus.c
OBJS_SERVER_BONUS = $(SRCS_SERVER_BONUS:.c=.o)
OBJS_CLIENT_BONUS = $(SRCS_CLIENT_BONUS:.c=.o)
NAME_SERVER_BONUS = server_bonus
NAME_CLIENT_BONUS = client_bonus

LIBFTPRINTF_DIR = ft_printf
LIBFTPRINTF = $(LIBFTPRINTF_DIR)/libftprintf.a

all: printf $(NAME_SERVER) $(NAME_CLIENT)

$(NAME_SERVER): $(OBJS_SERVER)
	$(CC) $(CFLAGS) -o $(NAME_SERVER) $(OBJS_SERVER) $(LIBFTPRINTF)

$(NAME_CLIENT): $(OBJS_CLIENT)
	$(CC) $(CFLAGS) -o $(NAME_CLIENT) $(OBJS_CLIENT) $(LIBFTPRINTF)

bonus: printf $(NAME_SERVER_BONUS) $(NAME_CLIENT_BONUS)

$(NAME_SERVER_BONUS): $(OBJS_SERVER_BONUS)
	$(CC) $(CFLAGS) -o $(NAME_SERVER_BONUS) $(OBJS_SERVER_BONUS) $(LIBFTPRINTF)

$(NAME_CLIENT_BONUS): $(OBJS_CLIENT_BONUS)
	$(CC) $(CFLAGS) -o $(NAME_CLIENT_BONUS) $(OBJS_CLIENT_BONUS) $(LIBFTPRINTF)

printf:

	make -C $(LIBFTPRINTF_DIR)

clean:

	rm -f $(OBJS_SERVER) $(OBJS_CLIENT)
	rm -f $(OBJS_SERVER_BONUS) $(OBJS_CLIENT_BONUS)
	make -C $(LIBFTPRINTF_DIR) clean

fclean: clean

	rm -f $(NAME_SERVER) $(NAME_CLIENT)
	rm -f $(NAME_SERVER_BONUS) $(NAME_CLIENT_BONUS)
	make -C $(LIBFTPRINTF_DIR) fclean

re: fclean all

.PHONY: all bonus printf clean fclean re